@baseURL = localhost:3001/api
### GET all blogs
GET {{baseURL}}/blogs

### GET One blog
GET {{baseURL}}/blogs/5a422a851b54a676234d17f7

### POST a blog
POST {{baseURL}}/blogs
Content-Type: application/json

{
  "title": "Jotain paskaa",
  "author": "Joku paska",
  "url": "jotainpaskaa.com",
  "likes": 0,
  "user":
}


### GET unkown endpoint
GET {{baseURL}}/blogs/simaa