@baseURL = localhost:3001/api
### GET all blogs
GET {{baseURL}}/blogs

### POST user
POST {{baseURL}}/users
Content-Type: application/json

{
  "username": "jyriBoi",
  "name": "Jyri Huhtala",
  "password": "salasana123"
}


### POST login
POST {{baseURL}}/login
Content-Type: application/json

{
  "username": "jyriBoi",
  "password": "salasana123"
}

### Delete blog
DELETE {{baseURL}}/blogs/6a64dc43d7531379abf682d5
