@baseURL = localhost:3001/api


### Get all persons
GET {{baseURL}}/persons

### Get person with id 1
GET {{baseURL}}/persons/1

### Get person with id 6a58bcee3f2e87b8be74dfe0
GET {{baseURL}}/persons/6a58bcee3f2e87b8be74dfe0

### Delete person with id 6a58bcee3f2e87b8be74dfe0
DELETE {{baseURL}}/persons/6a58bcee3f2e87b8be74dfe0

### Get person with nonexistng id 6a58bcee3f2e87b8be72dfe0
GET {{baseURL}}/persons/6a58bcee3f2e87b8be72dfe0

### Get person with nonexistent id 66
GET {{baseURL}}/persons/66

### Get info
GET {{baseURL}}/info

### Delete person with id 1
DELETE {{baseURL}}/persons/1

### Get all persons
GET {{baseURL}}/persons

### Post new person with valid phonenumber
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "Kari",
  "number": "040-123123"
}

### Post new person with invalid phonenumber
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "Kari",
  "number": "0100-100"
}


### Post person with too short name
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "O",
  "number": "0400-123123"
}

### Post existing person
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "Kari",
  "number": "0400-123123"
}

### Post existing person in lowercase
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "kari",
  "number": "0400-123123"
}

### Post person without a name
POST {{baseURL}}/persons
Content-Type: application/json

{
  "number": "0400111"
}

### Post person without a number
POST {{baseURL}}/persons
Content-Type: application/json

{
  "name": "Jari Karinen"
}


### Get all persons
GET {{baseURL}}/persons

### Get unknown endpoint
GET {{baseURL}}/monsters